#:schema node_modules/wrangler/config-schema.json
name = "ysl-worker"
main = "src/index.ts"
compatibility_date = "2024-04-23"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "kv"
id = "28f740f4a6974474b78f2e5805f857fc"
preview_id = "9f3ab85ca7824460a6e91458c8a972ef"
